/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hr_unizg_pmf_matrixcalc_ui_service_MatrixServiceClientImpl */

#ifndef _Included_hr_unizg_pmf_matrixcalc_ui_service_MatrixServiceClientImpl
#define _Included_hr_unizg_pmf_matrixcalc_ui_service_MatrixServiceClientImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     hr_unizg_pmf_matrixcalc_ui_service_MatrixServiceClientImpl
 * Method:    matMul
 * Signature: (Lhr/unizg/pmf/matrixcalc/ui/dto/MatrixDTO;Lhr/unizg/pmf/matrixcalc/ui/dto/MatrixDTO;)Lhr/unizg/pmf/matrixcalc/ui/dto/MatrixDTO;
 */
JNIEXPORT jobject JNICALL Java_hr_unizg_pmf_matrixcalc_ui_service_MatrixServiceClientImpl_matMul
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     hr_unizg_pmf_matrixcalc_ui_service_MatrixServiceClientImpl
 * Method:    matSolve
 * Signature: (Lhr/unizg/pmf/matrixcalc/ui/dto/MatrixDTO;Lhr/unizg/pmf/matrixcalc/ui/dto/MatrixDTO;)Lhr/unizg/pmf/matrixcalc/ui/dto/MatrixDTO;
 */
JNIEXPORT jobject JNICALL Java_hr_unizg_pmf_matrixcalc_ui_service_MatrixServiceClientImpl_matSolve
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     hr_unizg_pmf_matrixcalc_ui_service_MatrixServiceClientImpl
 * Method:    matPinv
 * Signature: (Lhr/unizg/pmf/matrixcalc/ui/dto/MatrixDTO;)Lhr/unizg/pmf/matrixcalc/ui/dto/MatrixDTO;
 */
JNIEXPORT jobject JNICALL Java_hr_unizg_pmf_matrixcalc_ui_service_MatrixServiceClientImpl_matPinv
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
